### ISSUE TITLE
Styles endpoint not returning anything

### ISSUE THREAD

**Issue by zeykafx** [openAIP/openaip#105]
Hi,
I'm trying to get the styles from the styles endpoint (e.g: https://api.tiles.openaip.net/api/styles/mono-style.json) but the styles listed on the page don't seem to exist, it just returns ` "message": "Maps style file mono-style.json not found"`
I would also like to know if I am doing something wrong, because the tiles don't seem to appear on my flutter app (using a library that supports .pbf files)
![Screenshot_20220122-171429](https://user-images.githubusercontent.com/37271973/150646764-e07efc7d-aa54-4cbd-b121-f7bdf29c67c1.jpg)
Thanks

**Comment by reskume** [comment]
Thanks for the report! The problem was a not up-to-date documentation. Please see the updated docs for more information.
The correct style names are "openaip-satellite-style" and "openaip-default-style".

**Comment by zeykafx** [comment]
Great, thanks for the quick answer!
