### ISSUE TITLE
Italy - Unexpected restricted area about Osiglia, Carcare, Cairo Montenotte, Millesimo, Cengio, Castelnuovo di Ceva, Murialdo 

### ISSUE THREAD

**Issue by starnutoditopo** [openAIP/openaip#138]
A circular restricted area from GND to 1500 AGL is reported near Osiglia, Carcare, Cairo Montenotte, Millesimo, Cengio, Castelnuovo di Ceva, Murialdo, centered about 44.349990,8.217430.
This seems not to appear on Enac's AIP, nor on maps by AAI (https://www.avioportolano.it).

**Comment by reskume** [comment]
Hi there and thanks for giving feedback! The airspace in question is `Bric Tana` which is actually listed in `ENR 5.6 BIRD MIGRATION AND AREA WITH SENSITIVE FAUNA`. Though obviously not considered by the two services you mentioned, there are following constraints for `Bric Tana` (quote from ENR 5.6):

> 1) Divieto di atterraggio, decollo e di sorvolo. Sono esonerati
dal divieto i seguenti voli: di soccorso, di emergenza, di
sorveglianza per la prevenzione degli incendi boschivi ed i voli
notificati/autorizzati dalle Autorità di zona (vedere i numeri
telefonici di Genova ATS/DA)/Restrictions to flight activity as
landing, taking off or overflying. Traffic not affected: rescue,
emergency and surveillance flights for forestal fire fighting and
flights notified/authorized by local Authorities (see phone
numbers of Genova ATS/DA).

Hope this clears the confusion.

Best wishes,

Stephan

**Comment by starnutoditopo** [comment]
Thanks very much for your reply and the detailed reference!

**Comment by reskume** [comment]
Though not directly related, this issue lead to discovering the bug #139 . So, thanks a again to you for pointing out! ;)

**Comment by starnutoditopo** [comment]
Good to know!
:-)

I have another concern about the "Bric Tana" zone.

According to ENR 5.6.1, pag 17 (
https://onlineservices.enav.it/enavWebPortalStatic/AIP/AIP/enr/enr5/ENR5-6-1.pdf
),
Bric Tana has a radius of 1200.0M. The circle in the map looks much larger
(I'd say about 5000.0M). (I'm not sure this to be ab issue, or just me not
able to read nautical information).

Hope this could be useful.

thanks again,
Stefano

**Comment by reskume** [comment]
Issue with radius is fixed.
