### ISSUE TITLE
French airspace errors and update

### ISSUE THREAD

**Issue by deltafox44** [openAIP/openaip#153]
Hi there, 

1 - There have been significant changes in French airspace on April 21th (see [Tours TMA](https://www.geoportail.gouv.fr/carte?c=-1.1635645876261262,46.768987535657715&z=9&l0=ORTHOIMAGERY.ORTHOPHOTOS::GEOPORTAIL:OGC:WMTS(1)&l1=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-OACI::GEOPORTAIL:OGC:WMTS(1)&permalink=yes) for instance). OpenAIP map is not up to date. Last FFVP OpenAIR file can be found (permanent link) [here](https://www.planeur.net/_download/airspaces/france.txt).

2 - There are errors in ceiling height in restricted airspace above National Parks which on AIP map is 1000ft AGL instead of 1000M AGL
see for instance "ECRINS 1000m/sol" which in the file is "AH 1000M AGL" and results in AIP map in "1000 FT GND"
![image](https://user-images.githubusercontent.com/82087770/167884925-944828fd-277d-4ae2-9c16-2a8261bfec16.png)

Thanks

**Comment by reskume** [comment]
Hi and thanks! The french airspace has been updated with the new data.
