### ISSUE TITLE
L to runways

### ISSUE THREAD

**Issue by Pops-67** [openAIP/openaip#165]
Runways should have L associated where applicable.

**Comment by reskume** [comment]
The current implemented logic allows adding suffix L(eft), R(ight) and C(enter) to each runway designator. See [EDDF Frankfurt Main](https://www.openaip.net/data/airports/62614a5e5e9ded5710443917) for reference. This is not a software but a dataset issue. If a document has incorrect or insufficient data, it can be directly edited by each logged in user via the web application. This is one of the main intention of openaip.

**Comment by Pops-67** [comment]
It's not about Left, Right. It's a navaid called "L" as in Locator beacon. It has a frequency and a position. Old school DME, sort of, but still exists several places.

**Comment by reskume** [comment]
Ah OK, didn't know this exists. My bad. Do you have an example how this would look like in the official AIP?

**Comment by reskume** [comment]
Fixed with #166
