### ISSUE TITLE
Runway instrument approach aids info

### ISSUE THREAD

**Issue by Pops-67** [openAIP/openaip#166]
Runway instrument approach aids should have the same info fields as other instruments aids:

**Comment by Pops-67** [comment]
Type, ID, HR, location, elev and rmk

**Comment by reskume** [comment]
Runway instrument landing aids now have more additional fields and added types. Since added location/elevation for each aid would require lots of new code with very litte added benefit for "real flying" I would postpone adding location/elevation until really required.
