### ISSUE TITLE
Instrument approach aids don't persist when saved

### ISSUE THREAD

**Issue by Pops-67** [openAIP/openaip#180]
For runways, saving instrument approach aids reports "OK", but they don't persist when saved

**Comment by reskume** [comment]
Works for me. Can you give an example or airport please? I just added the LOC27 to [Mannheim (EDFM)](https://www.openaip.net/data/airports/62614a87cb27f42509446445) without problems. Just to be precise: you have to press "Add approach aid", check that there is no required field missing, then add RFC comment, then press save (which I assume you did...)

**Comment by Pops-67** [comment]
Added LOC and DME at Andøya RWY 14. This time it seems the LOC persist (poosibly), but the DME disappeared (cant see it)
