### ISSUE TITLE
Missing updated airspaces in geojson file 

### ISSUE THREAD

**Issue by tomascern** [openAIP/openaip#186]
Hi, 

Recently I added new airspaces for the Czech republic: Kolín 1A, Kolín 1B, Kolín 1C, Kolín 1D, Kolín 2A, Kolín 2B, Kolín 2C, Kolín 2D. The change was applied and I can see the airspaces in openAip map. The problem is that the airspaces are not in the .geojson (cz_asp.geojson) nor .json files, but I can see them in .txt and .xml files.

**Comment by reskume** [comment]
I tried to reproduce this but worked for me. Steps done to reproduce:

1. Filter airspace list by search string "kol" OR filter by complete country "CZ"
2. Exported result list into all supported formats
3. Each exported file contains all airspaces from the filtered list

**Comment by tomascern** [comment]
I am using files from your scheduled data exports and the data are still missing there (https://storage.googleapis.com/29f98e10-a489-4c82-ae5e-489dbcd4912f).
