### ISSUE TITLE
UNLIM in airspace file

### ISSUE THREAD

**Issue by Pops-67** [openAIP/openaip#190]
The OpenAir format allows GND as 0 ft/m MSL. When inserting 0 ft/m and MSL as reference, it becomes GND. OpenAir also allows for UNLIM as upper limit, AH. But there is no way of entering UNLIM in the file. The openair file gets overwritten with whatever is set as AH in the field in the editor. AH can only be set as a numerical value.

**Comment by reskume** [comment]
Yes, this is intended behavior. The openaip airspace model does not allow UNLIMITED as in the openAIR format. To define an unlimited airspace use e.g. FL999 or whatever is defined in official AIP. This also cannot be fixed as the model requires a valid altitude value.
