### ISSUE TITLE
cup 2022 waypoint types

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#213]
Hello,

Thank you for your great work!

This is really an enhancement:
According to https://downloads.naviter.com/docs/SeeYou_CUP_file_format.pdf (2022 edition)

In the hgl export:
The waypoint type for:
Paragliding Takeoff is 20 
Paragliding Landing is 21

In the nav export:
I noticed that DME are exported as type 0
Example:
```csv
"HOCHWALD","HOC",CH,4728.000N,00739.900E,727.0M,0,,,113.200,"NAVAID, ID HOC, Frequency 113.200/79X, , Magnetic declination 2.831, Aligned to true north FALSE"
```
Now cup2022 doesn't have an explicit type for DME, but probably should be marked as VOR type 9

RPP:
These are now type 19 and are currenlty exported as type 1.

**Comment by reskume** [comment]
Thanks for the heads up! New types are available with the next scheduled data export tonight.
