### ISSUE TITLE
cup: rrp: comments not quoted, missing remarks

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#214]
Hello, 

Input for the RPP cup export:
* I have noticed that the comment field for the rpp export isn't quoted. The comma in the text is interpreted as a field separator, not showing part of the text in for example xcsoar:

![2022-07-15-003335_430x744_scrot](https://user-images.githubusercontent.com/407371/179099664-8ca4a1e4-3c1b-4ad0-8f41-18d55af0fa56.png)

* the remarks for the waypoint would make a great addition to the text field. 
* The type should be type 19 as reported in #213
Example:
```csv
"V","V",CH,4732.833N,00924.000E,396.0M,1,,,,Reporting Point, Non-Compulsory
"E","E",CH,4731.500N,00941.167E,396.0M,1,,,,Reporting Point, Non-Compulsory
"S","S",CH,4727.100N,00939.333E,405.0M,1,,,,Reporting Point, Non-Compulsory
"Z","Z",CH,4727.667N,00926.000E,578.0M,1,,,,Reporting Point, Non-Compulsory
"W","W",CH,4707.800N,00713.783E,430.0M,1,,,,Reporting Point, Non-Compulsory
```

**Comment by reskume** [comment]
Fixed with next scheduled data export.

**Comment by lordfolken** [comment]
Thank you for the fast fix!
