### ISSUE TITLE
Invalid VFR reporting points

### ISSUE THREAD

**Issue by migajek** [openAIP/openaip#223]
Hi,
recently I found some of the VFR reporting points in my local area to be placed incorrectly.
Let's focus on a single instance of this problem, that would be EPOK-L (LIMA OKSYWIE)
According to the AIP Poland VFR MIL, AD 4, EPOK, 7-3-1 Visual Operations Chart ( https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPOK_7-3-1_en.pdf ) the Reporting Point LIMA is "54 36 18N, 018 14 55E Wejherowo Town"
Google maps places the pin correctly for these coordinates: https://www.google.pl/maps/place/54%C2%B036'18.0%22N+18%C2%B014'55.0%22E

![image](https://user-images.githubusercontent.com/581492/183890132-8a5e30f5-58be-4a47-8b78-2e805ec858aa.png)

Unfortunately, as you can see below, OpenAIP places LIMA in Lesniewo town, which is some 6 NM north of actual location (Wejherowo)
![image](https://user-images.githubusercontent.com/581492/183889412-87da0062-63c3-4c8c-8ee9-88b34211d367.png)

I didn't do investigation, just verified following:
- the same issue is for the EPOK-W WHISKEY OKSYWIE point, which is around 2 miles south of it's actual location (is: SWARZEWO, Should be: WLADYSLAWOWO) 
- Other reporting poin in the area, EPOK-R ROMEO is in a correct location
- Yet another point- EPOK-K KILO is placed randomly over the sea. 
- OpenFlightMaps for instance show the correct palcement of the points

**Comment by reskume** [comment]
Hi and thanks for the feedback. Openaip allows adding and editing most of the  content that is available to the public. If you want you can correct the reporting points in question. To edit content on openaip, you need to create an account and login to the website. After a successful login, you can edit content via "view page -> Request Change -> Edit".

If you don't want to edit you can post the correct coordinates of the RRPs and I'll do it when I have some time.

**Comment by migajek** [comment]
Hi,
thank you for the instructions. The problem however appears to be more widespread. 
I am using Enroute navigation app which combines data from OpenAIP and OpenFlightMaps. Yesterday during a short flight I was able to spot more invalid points. 
I actually suspected there is some (semi)automated tool used to scrap the data from AIP to OpenAIP that might be buggy? Or maybe somebody did recently some data import that breaks the stuff? I suppose it might be worth to track down the source of the issue first.

For instance, the nearby EPPR airfield has the following misplaced points: K, W, R, S, P
I'll try to run crosscheck for all the points, assuming OpenFlightMaps has the correct ones

**Comment by reskume** [comment]
Hi,

VRPs have been imported from various sources several weeks ago. Main source
was a contributor that is offering a VFR navigation application. There have
been a lot of changes to VRPs in Austria and Norway according to the latest
AIP. Currently there is no automated process that imports data from AIP.
Ultimately the single source of truth is the official AIP to verify
correctness of each VRP. If you have doubt that VRPs for a specific airport
are wrong, please let me know. I can also check some points when I have
time ;)

Am Do., 11. Aug. 2022 um 08:19 Uhr schrieb Michał Gajek <
***@***.***>:

**Comment by migajek** [comment]
Thank you, will try to prepare the list.
I am using Enroute navigation which I believe compiles data from OpenAIP and OpenFlightMaps. Browsing the map I can see a lot of misplaced points around. Luckily Enroute displays points from both sources in a slightly different manner, so you can distinguish them. 
So far all the VRPs  in Enroute were solely from OpenFlightMaps. I've been using this app for a while now and never found an issue comparing to other maps, including official paper maps and Visual Ops Charts from AIP.

**Comment by migajek** [comment]
![IMG_20220811_085006](https://user-images.githubusercontent.com/581492/184079036-e203cb2a-6cdb-44c4-9b75-080423a8feeb.jpg)

**Comment by migajek** [comment]
Please find the results of crosscheck below. 
I have obtained points from both OFM and OpenAip. 
For the points existing in both sets, I've calculated the distance between them. Here's the list ordered by distance descending, where distance >= 0.2 NM.

I've verified a few random points with AIP and in every case the correct coordinates were in the OFM dataset.
Attached is the archive containing json dumps of the results (points missing in both sets + the distance analysis)

```
Reading OFM
Fetching OpenAIP
WARN EPPO-X has 2 entries
Comparing datasets
There are 204 points only in OFM, not in OpenAIP
There are 48 points only in OpenAIP, not in OFM
Total 179 points in common. Comparing
There are 24 misplaced points:
EPZP-S by 18,1NM
OFM  051°55'18"N 015°26'37"E    [51,9217        015,4436]
OAIP 052°07'18"N 015°48'37"E    [52,1217        015,8103]
AIP https://www.ais.pansa.pl/vfr/pliki/EP_AD_4_EPZP_en.pdf

EPPR-W MIL by 16,6NM
OFM  054°14'07"N 018°28'35"E    [54,2353        018,4764]
OAIP 054°15'24"N 018°56'50"E    [54,2567        018,9472]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPPR_7-3-1_en.pdf

EPZP-N by 16,3NM
OFM  051°59'47"N 015°27'56"E    [51,9964        015,4656]
OAIP 052°09'53"N 015°48'43"E    [52,1647        015,8120]
AIP https://www.ais.pansa.pl/vfr/pliki/EP_AD_4_EPZP_en.pdf

EPOK-K MIL by 14,6NM
OFM  054°46'11"N 018°09'37"E    [54,7697        018,1603]
OAIP 054°42'36"N 018°34'12"E    [54,7100        018,5700]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPOK_7-3-1_en.pdf

EPLY-N MIL by 10,9NM
OFM  052°03'11"N 019°10'07"E    [52,0531        019,1686]
OAIP 052°00'00"N 019°27'06"E    [52,0000        019,4517]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPLY_7-3-1_en.pdf

EPMM-S MIL by 10,2NM
OFM  052°08'60"N 021°39'59"E    [52,1500        021,6664]
OAIP 052°18'18"N 021°33'00"E    [52,3050        021,5500]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPMM_7-3-1_en.pdf

EPMB-J MIL by 5,9NM
OFM  054°07'21"N 019°17'45"E    [54,1225        019,2958]
OAIP 054°07'18"N 019°07'42"E    [54,1217        019,1283]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPMB_7-3-1_en.pdf

EPLK-B MIL by 4,9NM
OFM  051°20'36"N 019°22'35"E    [51,3433        019,3764]
OAIP 051°16'06"N 019°19'36"E    [51,2683        019,3267]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPLK_7-3-1_en.pdf

EPPR-P MIL by 4,1NM
OFM  054°07'08"N 018°46'02"E    [54,1189        018,7672]
OAIP 054°10'22"N 018°41'52"E    [54,1728        018,6978]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPPR_7-3-1_en.pdf

EPPW-S MIL by 3,6NM
OFM  052°18'39"N 017°49'00"E    [52,3108        017,8167]
OAIP 052°19'12"N 017°54'54"E    [52,3200        017,9150]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPPW_7-3-1_en.pdf

EPMM-O MIL by 3,6NM
OFM  052°07'26"N 022°01'20"E    [52,1239        022,0222]
OAIP 052°10'36"N 022°03'60"E    [52,1767        022,0667]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPMM_7-3-1_en.pdf

EPMM-M MIL by 3,5NM
OFM  052°06'28"N 021°49'40"E    [52,1078        021,8278]
OAIP 052°09'48"N 021°48'00"E    [52,1633        021,8000]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPMM_7-3-1_en.pdf

EPOK-H MIL by 3,4NM
OFM  054°36'37"N 018°47'56"E    [54,6103        018,7989]
OAIP 054°33'36"N 018°45'12"E    [54,5600        018,7533]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPOK_7-3-1_en.pdf

EPPR-K MIL by 2,6NM
OFM  054°19'19"N 018°46'34"E    [54,3219        018,7761]
OAIP 054°17'17"N 018°49'16"E    [54,2880        018,8212]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPPR_7-3-1_en.pdf

EPPR-S MIL by 2,1NM
OFM  054°11'06"N 018°40'57"E    [54,1850        018,6825]
OAIP 054°12'57"N 018°39'23"E    [54,2158        018,6563]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPPR_7-3-1_en.pdf

EPPW-N MIL by 1,9NM
OFM  052°27'28"N 017°53'28"E    [52,4578        017,8911]
OAIP 052°25'42"N 017°52'30"E    [52,4283        017,8750]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPPW_7-3-1_en.pdf

EPOK-W MIL by 1,8NM
OFM  054°47'25"N 018°24'30"E    [54,7903        018,4083]
OAIP 054°45'36"N 018°24'18"E    [54,7600        018,4050]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPOK_7-3-1_en.pdf

EPPR-R MIL by 1NM
OFM  054°08'54"N 018°54'17"E    [54,1483        018,9047]
OAIP 054°09'53"N 018°53'47"E    [54,1647        018,8963]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPPR_7-3-1_en.pdf

EPKK-Z by 0,9NM
OFM  050°06'33"N 019°46'46"E    [50,1092        019,7794]
OAIP 050°07'00"N 019°48'00"E    [50,1167        019,8000]
AIP https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPKK_7-3-1_en.pdf

EPKT-T by 0,7NM
OFM  050°21'00"N 018°51'00"E    [50,3500        018,8500]
OAIP 050°21'14"N 018°51'59"E    [50,3539        018,8664]
AIP https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPKT_7-3-1_en.pdf

EPOK-L MIL by 0,4NM
OFM  054°41'45"N 018°14'08"E    [54,6958        018,2356]
OAIP 054°41'48"N 018°14'54"E    [54,6967        018,2483]
AIP https://www.ais.pansa.pl/mil/pliki/EP_AD_4_EPOK_7-3-1_en.pdf

EPRZ-W by 0,4NM
OFM  050°03'52"N 021°43'52"E    [50,0644        021,7311]
OAIP 050°04'14"N 021°43'45"E    [50,0705        021,7292]
AIP https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPRZ_7-3-1_en.pdf

EPWA-E by 0,2NM
OFM  052°10'54"N 020°59'10"E    [52,1817        020,9861]
OAIP 052°10'42"N 020°59'00"E    [52,1783        020,9833]
AIP https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPWA_7-3-1_en.pdf

EPBY-S by 0,1NM
OFM  053°03'09"N 017°59'46"E    [53,0525        017,9961]
OAIP 053°03'09"N 018°00'00"E    [53,0525        018,0000]
AIP https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPBY_7-3-1_en.pdf
```

[crosscheck.zip](https://github.com/openAIP/openaip/files/9308973/crosscheck.zip)

**Comment by reskume** [comment]
Hi Michal,

will update content asap. Thanks a lot for diffing things!

Cheers,

Stephan

Am Do., 11. Aug. 2022 um 15:21 Uhr schrieb Michał Gajek <
***@***.***>:

**Comment by reskume** [comment]
Coordinates of VRPs have been fixed.

Am Mi., 17. Aug. 2022 um 09:02 Uhr schrieb Stephan Besser <
***@***.***>:
