### ISSUE TITLE
Downloading pbf tiles for a selected area

### ISSUE THREAD

**Issue by elgandoz** [openAIP/openaip#225]
I'm currently trying to download an extract of an area in a single .pbf file (in order to convert it via [OsmAndMapCreator](https://wiki.openstreetmap.org/wiki/OsmAndMapCreator) for displaying it in [OsmAnd](https://osmand.net/)).
I had a look at the swagger documentation for MBTiles, but I can't find a way to get an extract. Ideally I would like to provide 4 boundaries and download all levels of resolution.
Is there a way to currently achieve this?

**Comment by reskume** [comment]
The Tiles API provides PBFs for a requested area defined by the Z/X/Y url parameters. This endpoint is primarily intended to by used as a TMS that is integrated with a web map client or a GIS. OpenAIP exports the dataset daily into a GCS bucket. See [Scheduled Data Exports](https://www.openaip.net/develop) for more information on how to download the created MBTiles files. I suppose they are a better fit for this use-case though this is total guess....
