### ISSUE TITLE
PNG tiles are empty

### ISSUE THREAD

**Issue by StefanoOcchetti** [openAIP/openaip#228]
Downloading tiles using the provided test environment ( https://docs.openaip.net/?urls.primaryName=Tiles%20API ) or a production server ( such as https://a.tiles.openaip.net/ ) I always get a blank (transparent) png image (the response status code is OK 200).

The request is performed using a GET verb, specifying the proper x, y, z values, adding the accept=application/binary header and specifying the apiKey either as a URL query parameter or in the "x-openaip-client-id" header.

Example
```
Method: GET
RequestUri: 'https://a.api.tiles.openaip.net/api/data/obstacles/5/18/8.png?apiKey=xxxxxxxxxxxx'
Version: 1.1
Content: <null>
Headers:
  Accept: application/binary
```

**Comment by reskume** [comment]
The tiles should work. From what I see in the URL I assume that you are requesting tiles that either do not contain any obstacles or you are requesting tiles from a zoom level that is not supported by our TMS. Can you please check tiles with higher zoom levels? 

Another possible cause could be that your client uses some kind of TMS configuration parameter by default. In some cases, setting this specific TMS config parameter to either true or false may help with getting the correct tiles.

**Comment by reskume** [comment]
I'll close this issue since there was no feedback. If this is still a problem, feel free to re-open the issue.
