### ISSUE TITLE
Public use frequency

### ISSUE THREAD

**Issue by deltafox44** [openAIP/openaip#232]
When editing an airport frequency/Public use : the infobox

 `Enable this to indicate that the frequency is only intended for private use. By default, each frequency is considered to be public.` 

is misleading. It should be the opposite (**Disable** for private use) !
![Capture d’écran 2022-09-30 à 21 02 02](https://user-images.githubusercontent.com/82087770/193339768-ec66e066-4605-4c7c-aa27-696e4c64d0e2.jpg)

**Comment by reskume** [comment]
Valid point. Will fix this asap. Thanks for the feedback!
