### ISSUE TITLE
Add support for programs to read hours of operations

### ISSUE THREAD

**Issue by Wackymax** [openAIP/openaip#239]
We'd like it if OpenAIP could expose a programmatically readable field where hours of operations for airspaces could be stored. I would guess that most use cases can be covered by storing the hours for every day of the week. From what I could tell by looking at the various airspace names there can be one of 4 types for every day of the week:

- Entire Day (24H)
- Start/End time (e.g 05H00-22H30)
- Sunrise/Sunset (SR-SS+3H)
- By NOTAM

Some example airspaces are:
https://www.openaip.net/data/airspaces/62615b000e8346dfd9269b83?originUrl=%2Fdata%2Fairspaces%3Fpage%3D1%26limit%3D500%26sortDesc%3Dfalse

[https://www.openaip.net/data/airspaces/62614e42cb27f42509459f09?originUrl=%2Fdata%2F[…]ge%3D1%26limit%3D500%26sortDesc%3Dfalse%26search%3DTMZ%2520GG](https://www.openaip.net/data/airspaces/62614e42cb27f42509459f09?originUrl=%2Fdata%2Fairspaces%3Fpage%3D1%26limit%3D500%26sortDesc%3Dfalse%26search%3DTMZ%2520GG)

**Comment by reskume** [comment]
Feature is implemented the following:

- Airspaces may have hours of operation object
- Airports may have hours of operation object
- Navaids may have hours of operation object

Additionally, the map features an experimental filter to hide all currently inactive airspaces from the current map view.
