### ISSUE TITLE
Add an ID field to each OpenAIR airspace definition block

### ISSUE THREAD

**Issue by reskume** [openAIP/openaip#249]
Currently the only way to compare a specific airspace in two versions of a file is the AN field. This is error prone since this field is updated a lot. There is no real unique identifier in an OpenAIR airspace definition block.

Adding an unqiue ID field to each OpenAIR airspace definition block will help to identify each airspace in various versions of the same file. This change will also allow for partial updates from a new OpenAIR file version to the current country dataset in OpenAIP database,.

**Comment by speed-axel** [comment]
I also think, such an unique identifier would make the airspace handling easier. I'm just working on an airspace parser for Cumulus.

**Comment by reskume** [comment]
The new tag is still TBD but would be a big benefit for the format. OpenAIP already can export a new extended OpenAIR file via user manual exports. When everything is set with the new extensions to the format, we will switch to the new extended format also in the automated system exports.

**Comment by reskume** [comment]
Ticket closes when #259 is implemented.
