### ISSUE TITLE
Feature request: being able to sort by distance to reference point

### ISSUE THREAD

**Issue by rderimay** [openAIP/openaip#264]
IMO, it would be a great thing to be able to sort by distance for calls with a reference point and radius.
The current implementation forces you to ask for more results than needed to make sure you get enough results to sort yourself by distance once the call returns.

Let's assume you want to get the 5 nearest airports around your current location (to get the METAR and TAF for example). With the current implementation, as you virtually don't know how far and compact around you these airports could be, you will have to make a call with a big radius and a high result count, then sort them by ascending distance and take the first 5. 
The proposed sorting would allow to make only one call sorted by ascending distance and limited to 5 results.

**Comment by reskume** [comment]
This feature is available in the next version of the Core API which will be released with the new UI in the next weeks.

**Comment by reskume** [comment]
Will be release with #304 in the next weeks.
