### ISSUE TITLE
Obstacle Exports do not contain a Name in the waypoint

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#268]
Many waypoints in the obstacle db do not have a name.
https://github.com/XCSoar/XCSoar/blob/2e3e49be75cae354fc2ec2fbc524108a5fae3559/.github/workflows/build-native.yml#L420

```csv
name,code,country,lat,lon,elev,style,rwdir,rwlen,rwwidth,freq,desc
,,CH,4743.832N,00832.335E,841.0M,8,,,,"Height: 75 m GND "
,,CH,4712.319N,00840.403E,614.0M,8,,,,"Height: Unknown "
"Sendeturm Wasserflue","Sende",CH,4725.861N,00801.222E,844.0M,8,,,,"Height: 112 m GND "
,,CH,4724.137N,00808.568E,385.0M,8,,,,"Height: Unknown "
,,CH,4724.195N,00807.646E,375.0M,8,,,,"Height: Unknown "
,,CH,4728.559N,00839.608E,607.0M,8,,,,"Height: Unknown "
,,CH,4746.023N,00829.730E,615.0M,8,,,,"Height: Unknown "
,,CH,4730.102N,00845.878E,460.0M,8,,,,"Height: Unknown "
,,CH,4734.248N,00847.010E,409.0M,8,,,,"Height: Unknown "
```

Unfortunatly this is not according to the standard:

```
1 - Waypoint Name
key name: name
This field contains the long name of the waypoint. This must be unique and can not be left empty.
```

I would suggest a fallback value, such as obstacle? Or the OSMID?

**Comment by lordfolken** [comment]
The comment also contains an excessive whitespace. 

Btw: i have some demo code that build's an XCSoar repository from the dataexport with all the cup and openair files:
https://github.com/lordfolken/xcsoar-openaip-repogen/blob/master/xcsoar-openaip-repogen.py

**Comment by lordfolken** [comment]
Another idea is to add the height to the elevation if not already done. That way there would be something parsable for future collision warning options.

**Comment by reskume** [comment]
Thanks for the heads-up. The exported names are now either the actual name if not empty of "OBSTCL123" where 123 is the IDX of the loop. IDX will change depending on the number of items in the database. Excessive whitespaces have been removed. Also added missing CUP export functionality into the web UI.

**Comment by lordfolken** [comment]
Thanks for fixing this issues so super fast. :+1:
