### ISSUE TITLE
openaip hgl exports, no waypoint type set

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#269]
Hi, 

Looking at the HGL files there seems to be an error in the export:

The type is 0 but then there is 21,20 in the comment field which would be the correct type.

name,code,country,lat,lon,elev,style,rwdir,rwlen,rwwidth,freq,desc
 "ATTERRISSAGE MONTHEY","ATTER",CH,4614.901N,00657.993E,400.0M,0,,,,"21; Suitable for: Fixed Wind;"
"PLAN JACOT","PLAN ",CH,4655.138N,00647.941E,540.0M,0,,,,"21; Suitable for: Paraglider,Fixed Wind;"
"SIGNAL DE SOI","SIGNA",CH,4611.103N,00654.989E,1947.0M,0,,,,"20; Suitable for: Paraglider,Fixed Wind;"
"DÉCOLLAGE DE BELLEVUE","DÉCOL",CH,4614.969N,00654.270E,1688.0M,0,,,,"20; Suitable for: Fixed Wind;"
"STARTPLATZ URMIBERG S","START",CH,4700.732N,00835.425E,1115.0M,0,,,,"20; Suitable for: Paraglider;"
"STARTPLATZ URMIBERG S","START",CH,4700.738N,00835.481E,1111.0M,0,,,,"20; Suitable for: Paraglider;"

Btw: OpenAIP Data in XCSoar
![2023-01-29-130619_958x527_scrot](https://user-images.githubusercontent.com/407371/215325033-7376934a-32af-47c5-b0a0-410f17ba4d82.png)

**Comment by reskume** [comment]
To match the CUP format definition, we decided to use 0 aka "UNKNOWN" as type since there is no hang gliding field int the CUP types. I admit that export 20/21 in the description is suboptimal. We could also transform the enum value to the human readable one.

Really enjoying to see openaip data in xcsoar! Don't forget, if you need more details on airports and airspaces, we also offer the v2 JSON format that contains all metadata.

**Comment by lordfolken** [comment]
I see. 
There is an updated cup definition from naviter here: (2022)
https://downloads.naviter.com/docs/SeeYou_CUP_file_format.pdf

I see that there is a ParaGlider focus here:
20 PG Take Off
21 PG Landing

I would have support for those types in XCSoar. 

I was probably assuming falsely that PG Sites would be HGL suitable, but i guess higher speeds have different requirements. And hgl usually needs a ramp for takeoff.. 

Would it be possible to mark the ones which are PG exclusively with the PG values?

The comment field says:  "Fixed Wind" i assume this should be "Fixed Wing"?

**Comment by lordfolken** [comment]
The json format looks way more sane, than what has been attempted with cup. I hope to long term migrate to something like that. But that will take time and code changes in xcsoar.

**Comment by reskume** [comment]
Changs are implemented. The export now exports as follows:

```csv
name,code,country,lat,lon,elev,style,rwdir,rwlen,rwwidth,freq,desc
"STARTPLATZ WEST","START",DE,4845.385N,00824.390E,868.0M,20,,,,"Take-Off Site; Suitable for: Paraglider"
"KRAFTWERK LANDEPLATZ","KRAFT",DE,4803.023N,00806.292E,479.0M,21,,,,"Landing Site; Suitable for: Paraglider"
"RADSPITZE","RADSP",DE,5014.111N,01126.015E,656.0M,0,,,,"Take-Off Site; Suitable for: -"
"GLEITSCHIRM-LANDEPLATZ WEST","GLEIT",DE,4845.821N,00815.713E,261.0M,0,,,,"Landing Site; Suitable for: -"
"DRACHENFLIEGERPLATZ NEUMAGEN-DHRON","DRACH",DE,4952.645N,00653.263E,383.0M,0,,,,"Take-Off Site; Suitable for: Fixed Wing"

```
