### ISSUE TITLE
OpenAIR Airspace Exports - Values in AY and AC

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#271]
Hello,

Today i exported the swiss airspace in openair format and loaded it up in XCSoar. 

The AC field exported by openaip should only contain the Class of the airspace:

```
* AC class    ;    class = Airspace Class, see below:
*     R restricted
*     Q danger
*     P prohibited
*     A Class A
*     B Class B
*     C Class C
*     D Class D
*     GP glider prohibited
*     CTR CTR
*     W Wave Window
```

If there is a more accurate description like "TMA" it should be added with an addtional field "AY"

```
AY = Airspace Type (extends AC which should now only be used for class)
```
Example correct source:
```
AY TMA
AN TMA Alpnach 2 Tempo
AF 128.475
AG Alpnach Tower
AH FL130   
AL 700 m
DP 46:55:00 N 008:13:38 E
DP 46:53:24 N 008:14:30 E
DP 46:53:05 N 008:16:01 E
DP 46:48:34 N 008:11:51 E
DP 46:50:33 N 008:07:58 E
```

Openaip:
```
AC TMA
AN TMA ALPNACH 2 TEMPO
AL 2300ft MSL
AH FL130
DP 46:54:60 N 008:13:38 E
DP 46:53:24 N 008:14:30 E
DP 46:53:05 N 008:16:01 E
DP 46:48:34 N 008:11:51 E
DP 46:50:33 N 008:07:58 E
DP 46:54:60 N 008:13:38 E
```

**Comment by lordfolken** [comment]
Examples for AY
AY AWY
AY C
AY CTR
AY P
AY Q
AY R
AY RMZ
AY TMA
AY TMZ
AY W
```

**Comment by reskume** [comment]
I'll take a look into the issue asap. But out of curiosity, did you export to OpenAIR (extended) or did you export using default openAIR format? If the latter was used, it's expected behavior.

**Comment by lordfolken** [comment]
I reference the google drive. I.e. ch_asp.txt So its the openair files that are loaded there.
https://download.xcsoar.org/repository

```ini
name=US-ASP-national-OpenAIP.txt
uri=https://storage.googleapis.com/29f98e10-a489-4c82-ae5e-489dbcd4912f/us_asp.txt
type=airspace
description=OpenAIP Airspace for United States of America
area=US
update=2023-02-14T01:16:24.932Z
```

**Comment by reskume** [comment]
To not break backwards compat with other third-parties, openaip exports two types of openAIR file formats. The original one and the extended one. I assume the one you are interested in ist the extended one. File names are either "us_asp.txt" for the default and "us_asp_extended.txt" for the tensed format that contains non-standard token AG,AF and AY.

**Comment by lordfolken** [comment]
Thank you for the explanation. 

https://github.com/XCSoar/xcsoar-data-content/commit/4dfdb205025f4578e791a3f01afc14f43fb9f14d

I also discovered that XCSoar isn't even parsing the AY field. :(

https://github.com/XCSoar/XCSoar/issues/1118
