### ISSUE TITLE
OpenAIR Airspace Exports - Missing Frequency and Callsign fields (AF/AG)

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#272]
Hey!

The current export seem to be missing the airspace frequencies. 
Field AF
And the CallSign name
AG

Example:
```
* 08.03.2022 GSI
AC D
AY W
AN LS-R76 T Dittingen East
AF 118.180
AG Dittingen Aerodrom
AH 1525 m
AL 300 m AGL
DP 47:26:06 N 007:31:44 E
DP 47:27:00 N 007:39:00 E
DP 47:28:58 N 007:44:25 E
DP 47:25:52 N 007:46:41 E
DP 47:23:00 N 007:39:30 E
DP 47:23:43 N 007:32:32 E
```

**Comment by reskume** [comment]
I'll take a look into the issue asap. But out of curiosity, did you export to OpenAIR (extended) or did you export using default openAIR format? If the latter was used, it's expected behavior.

**Comment by lordfolken** [comment]
See same comment #271

**Comment by reskume** [comment]
To not break backwards compat with other third-parties, openaip exports two types of openAIR file formats. The original one and the extended one. I assume the one you are interested in ist the extended one. File names are either "us_asp.txt" for the default and "us_asp_extended.txt" for the tensed format that contains non-standard token AG,AF and AY.

**Comment by lordfolken** [comment]
duplicate #271
