### ISSUE TITLE
OpenAir export C/D Airspace Classes are exported as unclassified to the non-extended format

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#276]
Many airspaces in the classic format are labled as UNCLASSIFIED

Example:
```
*
* Hours Of Operation
* 24H
*
AC UNCLASSIFIED
AN DRESDEN
AL 3500ft MSL
AH FL75
DP 51:00:47 N 013:15:02 E
DP 51:28:29 N 013:53:01 E
DP 51:27:47 N 013:57:12 E
```

vs

```
AC D
AY UNCLASSIFIED
AN DRESDEN
AI 62614ad1cb27f42509447ebb
AF 125.875
AG München Radar
AL 3500ft MSL
AH FL75
DP 51:00:47 N 013:15:02 E
DP 51:28:29 N 013:53:01 E
DP 51:27:47 N 013:57:12 E
```

In my opinion this should be exported as AC D in the non-extended format. 

 to: ‘de_asp.txt’

de_asp.
http://winpilot.com/usersguide/userairspace.asp

http://winpilot.com/usersguide/userairspace.asp

**Comment by reskume** [comment]
Standard OpenAIR format now contains correct ICAO class. Issue has bee fixed. Next export files will contain the correct ICAO classes.
