### ISSUE TITLE
OpenAIR Airspace Danger and Restricted areas have UNCLASSIFIED as icao code

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#277]
All the Danger and Restricted zones are exported as 
AC UNCLASSIFIED
They should be 
```
* AC class    ;    class = Airspace Class, see below:
*     R restricted
*     Q danger
```

**Comment by lordfolken** [comment]
i just realized that R/Q are not part of ICAO, so this is correct.

**Comment by reskume** [comment]
For the extended version this is extended behavior. For the non-extended format AC R/Q should be present instead of AC UNCLASSIFIED. I'll take a look into this.

**Comment by reskume** [comment]
I assume that this ticket can be closed. R/Q are labeled as "UNCLASSIFIED" in the extended OpenAIR formatted file.
