### ISSUE TITLE
cup export for france contains too many quotation marks

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#293]
Hi, 

There is two lines in the french cup file:
```csv
"LE MANS ARNAGE","LFRM",FR,4756.920N,00012.102E,59.0m,5,020,1420.0m,30.0m,125.900,"AD reserved to ra      dio-equipped ACFT.\nSimultaneous use of both RWY prohibited.\nRestrictions during motor race ‘’24 he      ures du Mans’’ and others events "Le Mans Classic", "MOTO GP" (issued by NOTAM) ...etc."
```
The quoting combined with the comma, unfortunately messes up the field count and makes the file unparseable. 
It probably would be best to replace all double quotes(")  with single quotes in the field value and only add double quotes to enclose the value.

**Comment by reskume** [comment]
Fixed with current version of the Core API. Files will update today.
