### ISSUE TITLE
TACAN shows up as DME on map

### ISSUE THREAD

**Issue by Miningflo** [openAIP/openaip#301]
This issue exists on multiple TACANs in Belgium

For example:
[https://www.openaip.net/data/navaids/62616d87abdcc7f0ccbc0788](https://www.openaip.net/data/navaids/62616d87abdcc7f0ccbc0788)
is a TACAN Navaid

It looks like this on a map:
![image](https://github.com/openAIP/openaip/assets/13075141/9a5f60da-005d-4ded-a827-8278099f8b5d)

It is a DME according to the webpage
![image](https://github.com/openAIP/openaip/assets/13075141/d4249645-88b1-4ff0-9798-a21ae3f4dd07)

But if I click it to show more details, it suddenly changes into a TACAN
![image](https://github.com/openAIP/openaip/assets/13075141/c0a9883f-2771-41b3-8d8b-85257a72a369)
(Bonus issue: the range unit isn't displayed)

**Comment by reskume** [comment]
Fixed with latest release of the app. Map will take some time to update and reflect the changes.
