### ISSUE TITLE
Document airspace geojson format

### ISSUE THREAD

**Issue by tobiasgru** [openAIP/openaip#303]
Thank you for providing the airspace data in geojson format. It would be very nice if you could document the individual properties. e.g. what is the meaning of the numerical codes for upperLimit.unit, upperLimit.referenceDatum, what is dayOfWeek 0, what is the icaoClass numerical code  etc.

**Comment by reskume** [comment]
For the GeoJSON format, the enum values are the same as for the JSON format. The JSON format is documented here: [https://docs.openaip.net/](https://docs.openaip.net/)

To view the complete schema, please navigate to an endpoint that has the response schema that you are interested in, for example the airport GET endpoint: [https://docs.openaip.net/#/Airports/get_airports__id_](https://docs.openaip.net/#/Airports/get_airports__id_)

Then scroll down until you see the "Response" section. There you can see an example response. Above the actual response content you can see two links: "Example Value" and "Schema". Click on "Schema". You will find all enum values documented there.

Let me know if you need any further help and if I can close the ticket.

![Bildschirmfoto 2023-06-12 um 10 03 37](https://github.com/openAIP/openaip/assets/6482240/362b5552-f38e-48f0-91d3-84fc046ec6c2)

**Comment by tobiasgru** [comment]
thank you for the prompt answer. This mostly answers my question. DayOfWeek 0 is Sunday or Monday? Operating times  are in UTC?

**Comment by reskume** [comment]
Perfect! 0 is Monday. All times UTC. Feel free to reopen if you have other questions. Cheers!
