### ISSUE TITLE
Set map location by browser or user profile

### ISSUE THREAD

**Issue by cmw735** [openAIP/openaip#308]
At present OpenAIP seems to start in the middle of Germany, immediately requiring anyone who is not there to drag the map or enter co-ordinates. 
Provide an option to set the location via the user's browser, or by a location of the user's choice set in their profile.

**Comment by reskume** [comment]
Fixed in latest version v2.13.1

**Comment by cmw735** [comment]
Thanks, but how do I download /access this?
I can’t find any help about versions on the website.

Thanks,
Chris Ward

**Comment by reskume** [comment]
You cannot download this. The web-application over at https://www.openaip.net provides those features. The current version is `v2.13.2`. If you navigate to the map, the map will either set your current location that is detected by your browser or if set on your users profile page, it uses the `default map location` coordinates. Please note that you have to grant the openaip website permissions to use your browser to geolocate your position. Nowadays these browser features tend to be disabled by users or browser extensions / system preferences by default. If geolocate is not possible in your browser, a warning notification is shown. Granting permissions though is not in the scope of openaip app but solely the user.
