### ISSUE TITLE
VHF channels erroneously labeled as frequencies

### ISSUE THREAD

**Issue by thumax** [openAIP/openaip#310]
Throughout openAIP VHF channels are suffixed by “MHz” which suggests they are frequencies. They are not. When operated in 8.33 kHz channel spacing the “frequency” displayed on your radio is a channel number and not the actual center frequency.

Examples:
* EDDB Tower is listed as “118.805 MHz”, actual center frequency is 118.8000 MHz
* EDMD Info is listed as “133.010 MHz”, actual center frequency is 133.0083 MHz
* EDHO Info is listed as “127.560 MHz”, actual center frequency is 127.5583 MHz

Easy fix: just don’t add “MHz” to channel numbers.

**Comment by reskume** [comment]
Thanks for the heads up! Yes, we are aware of the fact that this is may not be correct in some cases - for countries that don't use 8.33 kHz spacing this is still valid. The current implementation is simply from the "time before 8.33 kHz" spacing in several countries.

For now, I admit it's a simple fix to remove the "MHz" suffix for the frequencies in the UI. The main big pain point is the backend and the API which still outputs frequencies with unit MHz. This is a big refactoring which in the end will result in a V2 API schema. I have created another issue to track the API schema refactoring here #311

**Comment by thumax** [comment]
Sure, thanks for the info!
