### ISSUE TITLE
Minor improvement for 'documentation' page

### ISSUE THREAD

**Issue by kebekus** [openAIP/openaip#316]
The section "Scheduled Data Exports" mentions the "GCS Bucket ID" and points the reader to libraries that can access the bucket. It might make sense to add a link to the Google Storage Browser, which is probably the easiest way to access the bucket.

- https://console.cloud.google.com/storage/browser/29f98e10-a489-4c82-ae5e-489dbcd4912f

Thanks for all your work!

Best,

Stefan.

**Comment by reskume** [comment]
Fixed in newest version.
