### ISSUE TITLE
Obstacles search page shows height as MSL instead of GND

### ISSUE THREAD

**Issue by shancock884** [openAIP/openaip#322]
When doing a search on the Obstacles search page, such as this link for 'Wotton-under-Edge BT Tower':
https://www.openaip.net/data/obstacles?page=1&limit=50&search=Wotton-under-Edge%20BT%20Tower
The table shows:
Height: 76 m MSL / Elevation Base: 232 m MSL / Elevation Top: 308 m MSL
But the height should say "GND" not "MSL", as the schema help says that datum is always GND for the obstacle height field.

The Json output appears to be correct, so I guess it is a webpage display issue:
```
      "height": {
        "value": 76,
        "unit": 0,
        "referenceDatum": 0
      },
      "elevation": {
        "value": 232,
        "unit": 0,
        "referenceDatum": 1
      },
```

**Comment by reskume** [comment]
Good catch! Fixed with the latest webapp version.
