### ISSUE TITLE
Bulk update Swiss airspace LSD and LSR Airspaces

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#327]
Hello, 

Due to harmonization of European airspace, the following change is necessary

Naming Convention LSR/LSD
Reason: Harmonization with European standards
• Removal of hyphen and spaces
• LS-R is now called LSR
• LS-D is now called LSD

Is there a way to bulk update this?

**Comment by reskume** [comment]
Hello!

I did this manually for Switzerland. Is this a EU wide change and also affects other countries like DE and FR?

**Comment by lordfolken** [comment]
I have this from the new charts and airspace refresher we run yearly in switzerland.
Glider chart: https://opendata.swiss/en/dataset/segelflugkarte-schweiz-1-300000
While this is according to EASA/SERA etc. i cannot comment on other nation's as i don't know where they are in the process at this time.

**Comment by reskume** [comment]
Ah, ok. Thanks for the clarification. Will check with the other airspace
maintainers.

Am Mo., 25. März 2024 um 23:51 Uhr schrieb Philipp Wollschlegel <
***@***.***>:
