### ISSUE TITLE
Duplicate Airspaces CTA-TOULHOUSE 1

### ISSUE THREAD

**Issue by lordfolken** [openAIP/openaip#352]
Hello, 

CTA-TOULOUSE 1-4 appear as
CTA-TOULOUSE 1
and 
CTA TOULOUSE 1

I can delete them via the interface, but just wanted to give a headsup in case this is a structural problem.

**Comment by reskume** [comment]
Hi and thanks for letting us know. You can comment on the airspace to be deleted. I'll remove asap.

**Comment by reskume** [comment]
Duplicates removed.
