### ISSUE TITLE
Add ability to include the phone number for listening to the ATIS

### ISSUE THREAD

**Issue by Vialonyx** [openAIP/openaip#377]
It would be interesting to add the possibility to include the phone number for listening to the ATIS in addition to the VHF frequency when one exists. This feature would be particularly useful for users who want to access ATIS by phone, as is the case for preparing flights between international airports.

**Feature description** :

- New field: Added a "Phone" field in the ATIS frequency entry form.
- Functionality: This field will allow users to enter a phone number associated with an airport's ATIS.
- Display: The "Phone" field will be displayed with other frequency informations.

**Implementation example** :
For the Bordeaux airport ATIS (LFBD), the "Phone" field could display a number such as +33 557928104 in addition to the VHF frequency 131.155 MHz.

![phone_atis_form_field](https://github.com/user-attachments/assets/9072ed1a-1819-4c24-bd5d-789db2b8990c)

Best regards

**Comment by reskume** [comment]
This feature will be released with the next big update in the next weeks. The airport model will contain a new property "telephoneServices" that can be used to add multiple services to an airport. the telephone service object contains the name, the phone number and a remarks property.
