### ISSUE TITLE
TEST FAIL: tests/convertAirspaces.test.js

### ISSUE THREAD

**Issue by hiltonsewell** [openAIP/openaip#380]
Is it just me? Does this test fail for you? Thanks :)

![image](https://github.com/user-attachments/assets/26afd669-bfad-4dca-bbb6-6f1dfb3755f4)

**Comment by reskume** [comment]
The test is from the aixm to geojson repo I think? Sorry, I'm only on phone
for the next days but the aixm to geojson repo is a work in progress and
will only support a small number of use cases.

Hilton Sewell ***@***.***> schrieb am Fr., 16. Aug. 2024,
19:22:
