### ISSUE TITLE
Airports: main runway designator frequently wrong

### ISSUE THREAD

**Issue by kebekus** [openAIP/openaip#86]
Dear all,

I found that the main runway designator in airport data structures is frequently wrong. For instance, in Bremgarten EDTG the 600m Grass runway 23 is declared as the main runway -- this is clearly very wrong. I also note that the other direction (600m Grass runway 05 is NOT declared as the main runway). 

In addition to fixing this issue, it might make sense to update the documentation, clearly stating if both or just one rwy direction is considered 'main'.

Best,

Stefan.

**Comment by reskume** [comment]
New logic now allows multiple runways being specified as main runway. Importing logic now correctly automatically determines a "main" runway. Considered main runway when importing is the longest runway, paved runways take precedence over unpaved ones.
