### ISSUE TITLE
Scandinavian TIA / TIZ airspaces are misclassified

### ISSUE THREAD

**Issue by kebekus** [openAIP/openaip#87]
Dear all,

the TIA and TIZ airspaces that exist in Scandinavia are misclassified as "OTHER" even though "TIA" and "TIZ" explicitly exist as possible entries for the "type" field.

Perhaps it might make sense to tweak the importer to look for the string "TIA" and "TIZ" in the airspace name?

Best,

Stefan.

**Comment by kebekus** [comment]
PS: For an example, search for "Skövde".

**Comment by reskume** [comment]
Relates to #88
