### ISSUE TITLE
Problem with Estonia ee airspaces

### ISSUE THREAD

**Issue by ReimarBauer** [openAIP/openaip#96]
Hi,
we found using airspaces of Estonia some entries with incomplete data.

The value of the unit is in this example missing.
```
  <NAME>AREA G5 (NARVA)</NAME>
  <ALTLIMIT_TOP REFERENCE="">
    <ALT UNIT="F"></ALT>
  </ALTLIMIT_TOP>
```
in our issue: https://github.com/Open-MSS/MSS/issues/1324 we solve this currently by skipping.

cheers
Reimar

**Comment by reskume** [comment]
Thanks for reporting this. Will take a look at this asap.
